# Generated by Django 3.2.5 on 2021-07-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210731_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfeirmCode',
        ),
    ]
