# Generated by Django 3.2.5 on 2021-07-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_confeirmcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfeirmCode',
        ),
    ]
